// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpwitiubqtoigzuytmxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd2l0aXVicXRvaWd6dXl0bXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTgxNDMsImV4cCI6MjA2NTU5NDE0M30.62Rn_7ZwjFXARqB3j_pD4pvEgd_S10Jx8s6JsGpkl8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);